exp_name: nyu_v2_2task
seed: [88, 45, 50, 100, 44, 48, 2048, 2222, 9999]
backbone: ResNet34
original_backbone: ResNet18
tasks: ["seg", "sn"]
lambdas: [1, 20]
tasks_num_class: [40, 3]
policy_model: task-specific

paths:
  log_dir: ../experiments/logs/
  result_dir: ../experiments/results
  checkpoint_dir: ../experiments/checkpoints

dataload:
  dataset: NYU_v2
  dataroot: "/home/kbardool/MLDatasets/nyu_v2"
  orig_dataroot: "/data/datasets/nyu_v2"
  crop_h: 321
  crop_w: 321

policy: True
init_neg_logits:
is_sparse: True
is_sharing: True
skip_layer: 0
is_curriculum: True
curriculum_speed: 3
fix_BN: False
diff_sparsity_weights: True
retrain_from_pl: False


train:
  batch_size: 32
  total_iters: 20000
  warm_up_iters: 4000
  lr: 0.001
  policy_lr: 0.01
  backbone_lr: 0.001
  reg_w: 0.05
  reg_w_hamming: 0.05
  print_freq: 100
  val_freq: 400
  decay_lr_freq: 4000
  decay_lr_rate: 0.5
  decay_temp_freq: 100
  init_temp: 5
  decay_temp: 0.965
  resume: False
  retrain_resume: False
  policy_iter: best
  which_iter: warmup
  init_method: equal
  hard_sampling: False

test:
  which_iter: best