exp_name:  NYU_v2_3Task_pretrain
seed: [88, 45, 50, 100, 44, 48, 2048, 2222, 23, 12, 94, 88, 1000, 42, 77, 666]
backbone: ResNet34
tasks: ["seg", 'sn', "depth"]
tasks_num_class: [40, 3, 1]
lambdas: [1, 20, 3]
policy_model: task-specific


paths:
  log_dir: /research/sunxm/IBM_mtl/experiments/logs/
  result_dir: /research/sunxm/IBM_mtl/experiments/results
  checkpoint_dir: /research/sunxm/IBM_mtl/experiments/checkpoints


dataload:
  dataset: NYU_v2
  dataroot: "/scratch/research/datasets/nyu_v2"
  crop_h: 321
  crop_w: 321

policy: True
init_neg_logits:
is_sparse: True
is_sharing: True
skip_layer: 0
is_curriculum: True
curriculum_speed: 3
fix_BN: False
diff_sparsity_weights: True
retrain_from_pl: False


train:
  batch_size: 16
  total_iters: 20000
  warm_up_iters: 4000
  lr: 0.001
  policy_lr: 0.01
  backbone_lr: 0.001
  reg_w: 0.001
  reg_w_hamming: 0.05
  print_freq: 100
  val_freq: 400
  decay_lr_freq: 4000
  decay_lr_rate: 0.5
  decay_temp_freq: 100
  init_temp: 5
  decay_temp: 0.965
  resume: False
  retrain_resume: False
  policy_iter: best
  which_iter: warmup
  init_method: equal
  hard_sampling: False


test:
  which_iter: best